DEFAULT:
  EXTENSIONS:
    - "jobskills.discord.flask:discord_extension"
    - "jobskills.discord.jobqueue:setup"
  scraper:
    scrapy:
      BOT_NAME: jobskills.scraper
      ROBOTSTXT_OBEY: false
      DOWNLOAD_DELAY: 3
      # pretend to be a real browser
      USER_AGENT: "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
      DEFAULT_REQUEST_HEADERS:
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Accept-Encoding: "gzip"
        Connection: keep-alive
        Upgrade-Insecure-Requests: 1
        Sec-Fetch-Dest: document
        Sec-Fetch-Mode: navigate
        Sec-Fetch-Site: same-origin
      REQUEST_FINGERPRINTER_IMPLEMENTATION: "2.7"
      FEED_EXPORT_ENCODING: utf-8
    domains:
      _default:
        spider: readability
        transform: "{}"
      indeed:
        spider: indeed
        transform: "https://webcache.googleusercontent.com/search?q=cache:{}"
    blacklists:
      readability: ["indeed"]
  discord:
    msg_max_len: 2000
DEVELOPMENT:
  redis: redis://localhost:6379
PRODUCTION:
  redis: redis://redis:6379
