version: '3.8'
services:
  app:
    # build:
    #   context: .
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "discord-endpoint"
      - "-b"
      - "[::]:8080"
    ports:
      - "8080"
    environment:
      - FLASK_DISCORD_CLIENT_ID_FILE=/run/secrets/discord_client_id
      - FLASK_DISCORD_CLIENT_SECRET_FILE=/run/secrets/discord_client_secret
      - FLASK_DISCORD_PUBLIC_KEY_FILE=/run/secrets/discord_public_key
      - TESTING_GUILD=1131850431883137044
      - REDIS_DSN=redis://redis
    secrets:
      - discord_public_key
      - discord_client_id
      - discord_client_secret
  scrape_worker:
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "scrape-worker"
    environment:
      - REDIS_DSN=redis://redis
  discord_worker:
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "discord-worker"
    environment:
      - REDIS_DSN=redis://redis
  redis:
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - '6379:6379'
secrets:
  discord_public_key:
    external: true
  discord_client_secret:
    external: true
  discord_client_id:
    external: true
