version: '3.8'
services:
  ngrok:
    image: ngrok/ngrok:3.3.4-alpine
    command:
      - 'start'
      - '--config'
      - '/run/secrets/ngrok_authtoken_config'
      - '--config'
      - '/ngrok_tunnel_config'
      - '--config'
      - '/ngrok_portainer_tunnel_config'
      - '--all'
    secrets:
      - ngrok_authtoken_config
    configs:
      - ngrok_tunnel_config
      - ngrok_portainer_tunnel_config
    ports:
      - "4040"
  proxy:
    image: caddy:2.7.4-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - ngrok_tunnel_bridge
secrets:
  ngrok_authtoken_config:
    external: true
configs:
  ngrok_portainer_tunnel_config:
    external: true
  ngrok_tunnel_config:
    external: true
networks:
  ngrok_tunnel_bridge:
    external: true
