version: '3.8'
services:
  app:
    # build:
    #   context: .
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "discord-endpoint"
      - "-b"
      - "[::]:8080"
    ports:
      - "8080"
    environment:
      - SECRETS_FOR_DYNACONF=/run/secrets/discord_creds.toml
      - TESTING_GUILD=1131850431883137044
      - ENVIRONMENTS_FOR_DYNACONF=production
    secrets:
      - source: discord_creds_toml
        target: discord_creds.toml
    networks:
      - ngrok_tunnel_bridge
  scrape_worker:
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "scrape-worker"
    environment:
      - ENVIRONMENTS_FOR_DYNACONF=production
  discord_worker:
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "discord-worker"
    environment:
      - ENVIRONMENTS_FOR_DYNACONF=production
  redis:
    image: redis:7.2.1-alpine3.18
    restart: always
    ports:
      - '6379:6379'
secrets:
  discord_creds_toml:
    external: true
networks:
  ngrok_tunnel_bridge:
    external: true
