version: '3.8'
services:
  app:
    # build:
    #   context: .
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "discord-endpoint"
      - "-b"
      - "[::]:8080"
    ports:
      - "8080"
    environment:
      - FLASK_DISCORD_CLIENT_ID_FILE=/run/secrets/discord_client_id
      - FLASK_DISCORD_CLIENT_SECRET_FILE=/run/secrets/discord_client_secret
      - FLASK_DISCORD_PUBLIC_KEY_FILE=/run/secrets/discord_public_key
      - TESTING_GUILD=1131850431883137044
      - REDIS_DSN=redis://redis
    secrets:
      - discord_public_key
      - discord_client_id
      - discord_client_secret
  scrape_worker:
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "scrape-worker"
    environment:
      - REDIS_DSN=redis://redis
  discord_worker:
    image: ghcr.io/rudyvane/jobskills:latest
    command:
      - "discord-worker"
    environment:
      - REDIS_DSN=redis://redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  ngrok:
    image: ngrok/ngrok:3-alpine
    command:
      - 'start'
      - 'discord_interactions'
      - '--config'
      - '/run/secrets/ngrok_authtoken_config'
      - '--config'
      - '/ngrok_tunnel_config'
    secrets:
      - ngrok_authtoken_config
    configs:
      - ngrok_tunnel_config
    ports:
      - "4040"
secrets:
  ngrok_authtoken_config:
    external: true
  discord_public_key:
    external: true
  discord_client_secret:
    external: true
  discord_client_id:
    external: true
configs:
  ngrok_tunnel_config:
    external: true
