version: '3.8'
services:
  ngrok:
    image: ngrok/ngrok:3.5.0-alpine
    command:
      - 'start'
      - '--config'
      - '/run/secrets/ngrok_authtoken_config'
      - '--config'
      - '/ngrok_tunnel_config'
      - '--config'
      - '/ngrok_portainer_tunnel_config'
      - '--all'
    secrets:
      - ngrok_authtoken_config
    configs:
      - ngrok_tunnel_config
      - ngrok_portainer_tunnel_config
    networks:
      - ngrok_tunnel_bridge
    ports:
      - "4040"
  proxy:
    image: caddy:2.7.6-alpine
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - ngrok_tunnel_bridge
secrets:
  ngrok_authtoken_config:
    external: true
configs:
  ngrok_portainer_tunnel_config:
    file: ./configs/ngrok_portainer_tunnel.yml
  ngrok_tunnel_config:
    file: ./configs/ngrok_discord_tunnel.yml
  caddyfile:
    file: ./configs/Caddyfile
networks:
  ngrok_tunnel_bridge:
    external: true
