DEFAULT:
  scraper:
    domains:
      _default:
        spider: readability
        transform: "{}"
      indeed:
        spider: indeed
        transform: "https://webcache.googleusercontent.com/search?q=cache:{}"
    blacklists:
      readability: ["indeed"]
DEVELOPMENT:
  redis:
    dsn: redis://localhost:6379
PRODUCTION:
