name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v5
      - uses: DeterminateSystems/nix-installer-action@v5
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          echo "matrix=$(nix eval --json '.#githubActions.matrix')" >> "$GITHUB_OUTPUT"
  nix-checks:
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v5
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build --print-build-logs --no-link ".#${{ matrix.attr }}"
