name: Deploy from main
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-id: ${{ steps.get-docker-id.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Login to ghcr.io
        run: |
          nix run .#skopeo -- login \
          -u '${{ github.actor }}' \
          -p '${{ secrets.GITHUB_TOKEN }}' \
          '${{ env.REGISTRY }}'
      - name: Deploy to ghcr.io
        run: "nix run .#deploy-image -- docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
      - id: get-docker-id
        name: Determine docker image tag
        run: |
          set -Eeu
          echo "tag=$(nix eval --json '.#docker-image.imageTag')" >> "$GITHUB_OUTPUT"
  production:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Substitute image tag
        run: |
          IMAGE_TAG=${{needs.docker.outputs.image-id}}
          sed -i "s/jobskills:latest/jobskills:$IMAGE_TAG/" docker-compose.yml
      - name: Push continuous tag
        run: |
          git checkout "$(git rev-parse HEAD)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docker-compose.yml
          git commit -m "continuous deployment"
          git tag -f continuous
          git push origin continuous -f