name: Deploy from main
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-id: ${{ steps.get-docker-id.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Login to ghcr.io
        run: |
          nix run .#skopeo -- login \
          -u '${{ github.actor }}' \
          -p '${{ secrets.GITHUB_TOKEN }}' \
          '${{ env.REGISTRY }}'
      - name: Deploy to ghcr.io
        run: "nix run .#deploy-image -- docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
      - id: get-docker-id
        name: Determine docker image tag
        run: |
          set -Eeu
          echo "tag=$(nix eval --json '.#docker-image.imageTag')" >> "$GITHUB_OUTPUT"
  production:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - run: echo "actually deploy ${{needs.docker.outputs.image-id}}"